# Generated by Django 2.1 on 2020-06-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('YearOfRelease', models.IntegerField()),
                ('Borrowed', models.BooleanField()),
                ('Returned', models.BooleanField()),
            ],
        ),
    ]
