# Generated by Django 2.1 on 2020-06-21 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LAMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='BorrowedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='book',
            name='ReturnDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
